import { ITask } from '../../store'

const data: Array<ITask> = [
  {
    id: 1,
    title: 'Conferir o novo desafio 🚀 ',
    desc: 'Conferir o novo projeto do #boraCodar para fazê-lo da melhor maneira possível',
    status: 'pending',
    status_list: 'pendingTasks',
    created_at: '2023-15-04',
    updated_at: '2023-15-04',
  },
  {
    id: 2,
    title: 'Conferir o novo desafio 🚀 ',
    desc: 'Conferir o novo projeto do #boraCodar para fazê-lo da melhor maneira possível',
    status: 'in progress',
    status_list: 'inProgressTasks',
    created_at: '2023-15-04',
    updated_at: '2023-15-04',
  },
  {
    id: 3,
    title: 'Conferir o novo desafio 🚀 ',
    desc: 'Conferir o novo projeto do #boraCodar para fazê-lo da melhor maneira possível',
    status: 'in progress',
    status_list: 'inProgressTasks',
    created_at: '2023-15-04',
    updated_at: '2023-15-04',
  },
  {
    id: 4,
    title: 'Conferir o novo desafio 🚀 ',
    desc: 'Conferir o novo projeto do #boraCodar para fazê-lo da melhor maneira possível',
    status: 'in progress',
    status_list: 'inProgressTasks',
    created_at: '2023-15-04',
    updated_at: '2023-15-04',
  },
  {
    id: 5,
    title: 'Conferir o novo desafio 🚀 ',
    desc: 'Conferir o novo projeto do #boraCodar para fazê-lo da melhor maneira possível',
    status: 'done',
    status_list: 'doneTasks',
    created_at: '2023-15-04',
    updated_at: '2023-15-04',
  },
  {
    id: 6,
    title: 'Conferir o novo desafio 🚀 ',
    desc: 'Conferir o novo projeto do #boraCodar para fazê-lo da melhor maneira possível',
    status: 'done',
    status_list: 'doneTasks',
    created_at: '2023-15-04',
    updated_at: '2023-15-04',
  },
  {
    id: 7,
    title: 'Conferir o novo desafio 🚀 ',
    desc: 'Conferir o novo projeto do #boraCodar para fazê-lo da melhor maneira possível',
    status: 'pending',
    status_list: 'pendingTasks',
    created_at: '2023-15-04',
    updated_at: '2023-15-04',
  },
  {
    id: 8,
    title: 'Conferir o novo desafio 🚀 ',
    desc: 'Conferir o novo projeto do #boraCodar para fazê-lo da melhor maneira possível',
    status: 'pending',
    status_list: 'pendingTasks',
    created_at: '2023-15-04',
    updated_at: '2023-15-04',
  },
]

export { data }
